---
- name: "install shadow"
  apt:
    name: shadowsocks-libev
    state: present
  become: true
  become_method: sudo
- name: "Setup config.json file"
  template:
    src: "files/config.json.j2"
    dest: "/etc/shadowsocks-libev/config.json"
  become: true
  become_method: sudo
