---
# tasks file for create-certs
- name: "install snap"
  apt:
    name: snapd
    state: present
  become: true
  become_method: sudo
- name: "start snap"
  ansible.builtin.systemd:
    name: snapd
    state: started
  become: true
  become_method: sudo
- name: "install snap core"
  community.general.snap:
    name: core
    state: present
  become: true
  become_method: sudo
